### PR TITLE
Please review - Pages built but NO CSS.

### PR DESCRIPTION
**Pull request by Hawkbit**
Don't merge until you've reviewed. There's errors; see readme.

### CODE REVIEW

**Comment by HowardSnowden** [comment]
Cool, I should be able to review when I get a chance to get on my laptop.
So to review without merging to the main branch, do you know what the steps
should be? Create a branch on my local repository and pull to that
repository before merging locally and then push?

**Comment by Hawkbit** [comment]
https://help.github.com/categories/collaborating/

That's a good list of collaboration FAQs. This one: https://help.github.com/articles/using-pull-requests/

I haven't done it myself, so I'm only guessing. I think there's a way to branch it off the master so you can view it locally. I'm still searching.

EDIT: https://sethvargo.com/checkout-a-github-pull-request/

We can do this tonight if you want when we're going to host the site.

**Comment by HowardSnowden** [comment]
Okay, that last article is exactly what I was thinking of, I will try that
out when i get home.

**Comment by HowardSnowden** [comment]
Okay, I fixed the delete method for the app, let me know when you want to
meet.

The delete not working was kind of my fault, the javascript include tag in
the header wasn't working for me when I was working on importing the
database, so I deleted it I since put it back in and was able to make it
work by putting changing the coffee-script-source to 1.8.0. The delete
method relies on the that 'are you sure' dialog box, so since it couldn't
use that, it just performs the show action instead.

**Pull request merged**
